#!/bin/bash
echo ".\" Man Page for _printf
.TH _PRINTF 3 "March 2024" "Version 1.0" "_printf User Commands"

.SH NAME
_printf \- custom printf function


.SH SYNOPSIS
.B #include <stdio.h>
.PP
.B int _printf(const char *format, ...);


.SH DESCRIPTION
The \fB_printf\fR function writes output to the standard output stream according to a format string. It is similar to the standard library printf function, but with some differences.
The \fIformat\fR parameter is a character string that contains two types of objects: plain characters, which are simply copied to the output stream, and conversion specifications, each of which results in fetching zero or more arguments from the variable argument list passed to \fB_printf\fR. Conversion specifications start with a percent sign (%) and are followed by optional format flags and a conversion character.

The conversion characters supported by \fB_printf\fR are as follows:


.TP
.B %c
Print a single character.
.TP
.B %s
Print a null-terminated string.
.TP
.B %d, %i
Print a signed decimal integer.
.TP
.B %%
Print a percent sign.


.PP
The behavior of \fB_printf\fR can be modified by using various format flags, such as the field width, precision, and justification. Refer to the standard printf documentation for more details.
.SH RETURN VALUE
The \fB_printf\fR function returns the total number of characters written on success. On failure, it returns a negative value.

.SH EXAMPLES
To print a string:
.PP
.nf
.B #include <stdio.h>
.br
.B int main(void) {
.br
.B _printf("Hello, world!\n");
.br
.B return 0;
.br
.B }
.fi

.SH SEE ALSO

.BR printf (3)
.SH BUGS
There are currently no known bugs.
.SH AUTHOR
Your Name <pakizemutellimova97@mail.ru>
.br
Group Mate's Name <kenanshafizade85@gmail.com>
.SH COPYRIGHT
Copyright \(co 2024 Pakiza Mutallimova and Kanan Shafizada.

>man_3_printf.2
mv man_3_printf.2 /usr/local/man/man1/
gzip -f /usr/local/man/man1/man_3_printf.2
man man_3_printf
